"""second

Revision ID: 39c574fb2952
Revises: 342cd14ebe4e
Create Date: 2015-04-02 12:57:10.687232

"""

# revision identifiers, used by Alembic.
revision = '39c574fb2952'
down_revision = '342cd14ebe4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testval', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testmodel')
    ### end Alembic commands ###
