"""avatar cache

Revision ID: 3a82c8d463ee
Revises: 1cc7e0a80345
Create Date: 2015-07-10 15:38:05.421467

"""

# revision identifiers, used by Alembic.
revision = '3a82c8d463ee'
down_revision = '1cc7e0a80345'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
